spring.application.name=localzero

spring.datasource.url=jdbc:postgresql://postgres.mau.se:55432/feja

spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:application-secret.properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fridalarsson25@gmail.com
spring.mail.password=pgdm lhkx ardn tydk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false