


spring.application.name=localzero

spring.datasource.url=jdbc:postgresql://postgres.mau.se:55432/feja

spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:application-secret.properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

server.port=8081